exclude: '^$'
default_stages: [push]
repos:

- repo: https://github.com/crazy-matt/pre-commit-manager
  rev: v1.0.0
  hooks:
  - id: detect-unsigned-commit
    exclude: '^$'
    stages: [commit]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-merge-conflict
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: check-yaml
  - id: detect-private-key
  - id: detect-aws-credentials

- repo: https://github.com/Yelp/detect-secrets
  rev: v1.1.0
  hooks:
  - id: detect-secrets
    exclude: '^$'

- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.7.2
  hooks:
  - id: shellcheck
    args: ['--severity=warning'] # Only show errors and warnings
